- Documentation/changelog.md
Create: Created a Documentation folder which has a changelog.md folder in it. So we can keep track on what has happenend when.
> Create: Documentation Folder

- Documentation/changelog.md
- Scripts/pcHealth.bat
Create: Main Batch Code has been added to the Repository.
It still needs some improvement. It works and the user can interact with the menu. But the user has to be able to go back to the previous menu when a command has been ran.
Instead of closing and re-opening.
> Create: Main Code

- Documentation/changelog.md
Update: I have added some new text to the changelog.md
> Update: Changelog.md

- Scripts/pcHealth.bat
Update: Added a function to check your battery status.
> Update: Added Battery Report

- README.md
Update: Updated the README.md file. So it explains what this repository is about, what the script it main purpose is. And there are labels placed in the README.md.
> Update: Updated README.md

- Documentation/changelog.md
Update: Updated the Changelog.md to let users understand what this repo is about and how/why to use the .bat file.
> Update: Updated Changelog.md

- Documentation/changelog.md
- Scripts/pcHealth.bat
Add: Added a return to menu function.
> Add: Return Function

- Documentation/changelog.md
- Scripts/pcHealth.bat
Update: Updated/Added/Tweaked the code.
A new function has been added; to let you scan and repair right after eachother.
Tweaked how the code worked, it should be more streamlined.
Updated the code as stated above and updated the changelog.md file.
> Update: Main Code

- Documentation/changelog.md
- Scripts/pcHealth.bat
Tweak: Added function 5, so users know how to exit the batch file.
> Tweak: Added function 5

- Documentation/changelog.md
- Scripts/pcHealth.bat
Updates & Tweaks: Updated how the main code works and displays. Tweaked main code too.
Added some improvements for future implementations. (Added a return to menu after a process has been ran)
> Update & Tweak: Main Code

- Scripts/pcHealth.bat
Tweak: Added a Space after the ENTER.
> Tweak: Tweaked Space's

- Documentation/changelog.md
- Scripts/pcHealth.bat
Add: Added an open battery log function.
> Add: Open Battery Log Function

- Documentation/changelog.md
- README.md
- Scripts/pcHealth.bat
Update: Updated the main code. Added the function to open a CBS.log to read which error's came up. You can also redirect back.
Updated the changelog.md
Added a link to the README.md file with a link to my other 'older' repository.
> Update: Multiple Updates

- Documentation/changelog.md
- Scripts/pcHealth.bat
Update: Updated the way logs open and when they open. Updated the menu's that gives the user the ability too.
> Update: Opening Logs

- Documentation/changelog.md
- Documentation/releases.md
Add: Added a new file to the documentation folder. Which keeps track on the latest releases.
> Add: Added releases.md

- Documentation/changelog.md
- Scripts/pcHealth.bat
Add: New function has been added, you can now get your Ninite through the terminal. It will start the download immediatly. Edge, Chrome, VLC and 7Zip will download to your device.
> Add: New Function - Ninite

- Documentation/changelog.md
- Scripts/pcHealth.bat
Add: Added the force admin feature.
the program will be aware and can tell if it is being launched in administrator mode or not. 
When this isn't the case the prompt will ask the user to give it administrator rights.
> Add: Added Forced Admin Feature

- Documentation/changelog.md
- Documentation/releases.md
- README.md
Update: Updated the documentation.
> Update: Documentation

- Scripts/pcHealth.bat
> Update: Updated the version

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/pcHealth.bat
Update: Maintenance on the Code
> Update: Maintenance on Code

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/pcHealth.bat
Update: Main Code has been updated to display the full version release when opened. 
Documentation has been updated due to the same reason.
> Update: Main Code & Documentation

- Documentation/changelog.md
- Documentation/releases.md
- LICENSE
- README.md
- Scripts/pcHealth.bat
Add: Added the function to open the GUI to the Windows Update section within the script.
> Add: Open Windows Update Function

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Add: Added 2 ping features/commands.
Updated the README.md / Changelog.md
> Add: Added 2 Ping Features

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Add: Added a system info command so you can gather the information about the pc.
> Add: SYSINFO Command

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/pcHealth.bat
Update: Updated releases.md - so it shows on which build we are and which were the previous builds.
> Update: releases.md

- Scripts/pcHealth.bat
Update: Updated and changed the main code... and the color will change when initiating a command.
> Update: Color/Main Code

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Add: Added a Log off, Restart and/or Shutdown feature. 
To give the user the ability to be able to do these function through the CMD/Script.
> Add: Log off, Restart and/or Shutdown Feature

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Add: Added GPUINFO feature to the script. So the user can check which GPU is in the system.
> Add: Added GPUINFO Feature

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Update: Updated the Documentation and version information.
> Update: Documentation and Version info

- README.md
Tweak: Fixed Typo in the README.md tagg.
> Tweak: Fixed Typo README.md

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/pcHealth.bat
Tweak: GPU command also shows CPU information. Documentation files are updated.
> Tweak: GPU Command to CPU&GPU

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Updated the RESHUT function to close the script after the user has made a choice.
> Tweak: RESHUT Function

- Scripts/CMD/pcHealth.bat
Update: Updated the Visual representation of on which version the user is. (.bat file)
> Update: Visual Version

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Updated the visual appearance of the code. So it's prettier and easier to read for the user what he/she is about to do.
The code was a bit hard to read in the past, we hope to have adressed that issue.
There might be a possibility that there will be more reworks on the visual front.
> Tweak: Visual Appearance - Code

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/PowerShell/pcHealth.ps1
Update: Updated the PowerShell script so it has some functions and can be used... not advised but there are some features that work now.
> Update: PowerShell Functions

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added a new function which runs a line of code to gather the systems license key. This is so you possibly can re-install and enter this product code of Windows to re-activate your Windows iso.
> Add: Added License Key Grabber

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added a new function which opens a sub-menu with direct links to downloadable programs which can be very usefull to run and diagnose problems on a system.
> Add: Downloadables Function

- Documentation/changelog.md
- Scripts/CMD/pcHealth.bat
Update: Updated some text issues that were displaying when running the script. (v1.3.7-beta)
> Update: Visual Representation

- README.md
I don't know if you're interested to use this, but when scrolling through the readme, this were some things that struck me.
> feat(readme): clarify instructions

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked the HWinfo download link.
> Tweak: Tweaked HWinfo

- Scripts/CMD/pcHealth.bat
Tweak: Updated the displayed version in the script.
> Tweak: Version updated

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Update: Updated the main code, made it easier to navigate through the code.
There are 2 menus that have options inside their menus.
> Update: Refresh of Main Code

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Update: Finally REWORK 2.0 has been forfilled and completed.
Enjoy the newest version of pcHealth!
It is a bit more streamlined and up to speed. Besides that the README.md has seen some daylight to.
> Update: REWORK 2.0

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked the colours in the menus to display some colours that are somewhat easier to look at.
> Tweak: Colours

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Resolved some small issues regarding to the text displaying and visual representation (color)
> Tweak: Resolved some issues

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked some minor errors.
> Tweak: Minor Changes

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added the audio feature regarding restarting the drivers from the host.
> Add: Audio Feature

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Resolved an issue regarding to returning to a sub-menu in the ''programs' section.
> Tweak: Resolved Issue

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added a way to update system programs via command line.
> Add: Update System Functions

- Documentation/changelog.md
- README.md
- Scripts/CMD/pcHealth.bat
Tweak: Fixed an issue regarding the script crashing when trying to run the '10' function in the Tools menu.
> Tweak: Fixed Issue

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Update: Updated all the files that need to be updated before pushing a full release.
> Update: Updated Documents - v1.5.4

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added a new function users can use.
BIOS-PW, a website that has a database behind it which containts a lot of BIOS password reset keys for specific laptops.
> Add: BIOS-PW

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked the newly added function to execute better.
> Tweak: Updated Function

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Made some small adjustments to the script. 
Changed some of the colours to change things up a bit.
Fixed some small typo's too...
> Tweak: Small Adjustments

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/PowerShell/pcHealth.ps1
Add: Added some small features regarding to the 'un-loved' PowerShell script.
> Add: Added Some Features

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
QoL: Simple quality of life update regarding some small problems that were present in the script.
> QoL: Minor Changes

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
> Tweak: Changed Colors

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Add: Added new functions to the script.
> Add: New Functions

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked some minor inconvieniences regarding to the new functionality that the Script got... Thanks for pointing it out @REALSDEALS
And I have updated the README.md in this instance.
> Tweak: Solved Problems

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Update: Added new functions to the script.
> Update: Added new functions

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
> Fix: Buggs Demolished

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Add: Added a simple menu title to display to the user in which menu he/she is.
> Add: Menu Title

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Tweaked the menu titles to be centered. This makes it more easy to see and read.
> Tweak: Menu Title Centered

- Documentation/changelog.md
- Scripts/PowerShell/pcHealth.ps1
Add: Added functionality to the .PS script. DiskCheck, DISM and SFC have been intergrated.
Function 5 and 6 in the pcHealth.ps script.
> Add: DiskCheck, DISM and SFC

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/PowerShell/pcHealth.ps1
Update: Updated the version numbers in the documentation and scripts.
> Update: Version Control

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Add: Added the user definable trace and ping function. So the user can choose a url to their likings to trace and ping.
> Add: User defined Trace and Ping

- Documentation/changelog.md
- Documentation/releases.md
Review: Checked the script, will be releasing a final release soon.
> Review: Checked Script

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added new functions; ipconfig to show the users their ip and tracert designated; to let the user specify a URL to trace too.
> Add: IPCONFIG & TRACERT DESIGNATED

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: Added a auto run VBS function, to the Programs menu.
> Add: Auto Run VBS

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
- Scripts/VBS/KeyGrabber.vbs
Tweak: Updated the download links in the download tools sub-menu.
> Tweak: Updated Download Links

- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
Add: A new addition has been added to the Tools menu; Windows PowerToys can now be installed through the Tools menu  section.
> Add: Windows PowerToys Installation

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Tweak: Minor adjustments to some generic code.
> Tweak: Environmental Variables

- Scripts/CMD/pcHealth.bat
Tweak: Reformated the way the script greets the user.
> Tweak: Reformat 'Hello'

- Documentation/changelog.md
- README.md
Tweak: Changed the discord username in the README.md - since Discord discontinued the use of the #tag.
> Tweak: Discord User Tag

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
**Release Update:** A full version release can be released. 
The past changes are checked and have been flagged as working.
Since it has been a long time since we have a had a check-up/full release we are releasing a new full release.
_From v1.7.0 to v1.8.3._
> Release Update: pcHealth - v1.8.3

- .github/ISSUE_TEMPLATE/bug_report.md
- Documentation/changelog.md
- Documentation/releases.md
- README.md
- Scripts/CMD/pcHealth.bat
- Scripts/PS1/Get-CPU_GPU_RAM.ps1
- Scripts/VBS/KeyGrabber.vbs
- Fixed broken downloader links.
- Changed the username variable logic so the script can read the full username.
- Improved the program updater; it now uses a more verbose logic. It will tell you what it is doing and if it is successful or not.
- Changed the Ninite downloader to download and run the installer directly. This is faster and doesn't give a flashing browser window.
- Changed some strings/names.
- Migrated more components to Winget to ensure correct downloadlinks.
- Changed how CPU, GPU, and RAM details are displayed.  
Refer to [this article](https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242) for more information. Microsoft is deprecating the WMIC command line tool, which is used to retrieve CPU, GPU, and …
> Some big enhancements

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Update: In preparation for the beta release to test the new featureset and the rework of code that @Stensel8 provided.
> Update: Beta Release (v1.8.4)

- Documentation/changelog.md
- Scripts/CMD/pcHealth.bat
- Scripts/PS1/Get-CPU_GPU_RAM.ps1
- Enhance winget updater/upgrader: automatically accept source and package agreements to avoid extra prompts.
> Changed winget behaviour + Performance improvements

- Documentation/changelog.md
- Documentation/releases.md
- Scripts/CMD/pcHealth.bat
Update: A small and simple update to the 'code', as usual, when a new beta release is on schedule.
> Update: Beta Release v1.8.5-beta
